# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: waka.cloudis::montage.form_name

# Model Form Field configuration
form: $/waka/cloudis/models/montage/fields.yaml

# Model Class name
modelClass: Waka\Cloudis\Models\Montage

# Default redirect location
defaultRedirect: waka/cloudis/montages

# Create page
create:
    title: waka.cloudis::montage.create
    redirect: waka/cloudis/montages/update/:id
    redirectClose: waka/cloudis/montages
    form: $/waka/cloudis/models/montage/fields_create.yaml

# Update page
update:
    title: waka.cloudis::montage.update
    redirect: waka/cloudis/montages/update/:id
    redirectClose: waka/cloudis/montages

# Preview page
preview:
    title: waka.cloudis::montage.preview_name
