# ===================================
#  Btn  Behavior Config
# ===================================


modelClass: Waka\Cloudis\Models\Montage

workflow: false 

###BREADCRUMP
breadcrump:
    inSettings: true 
    indexUrl: waka/cloudis/montages
    indexlabel: waka.cloudis::montage.title
    title: waka.cloudis::montage.form_name

###TOOL_BAR
tool_bar:
    base:
        create: 
            show: true
            permissions: [waka.cloudis.admin.super]
            url: waka/cloudis/montages/create
        reorder: 
            show: false 
        delete: 
            show: true
            permissions: [waka.cloudis.admin.super]
    config_btns:
            format: all
            btns:
    config_lot:
        format: all
        btns: 
    # partials: #Attention seul les variables modelId et modelClass (class du controller) sont disponible sans les partials.  
    #     testbtns:
    #         url: $/waka/cloudis/controllers/montages/_test_btns.htm

###ACTION_BAR Producteurs. Les behavior liée aux boutons doivent êtres instanciés implements = [waka.xxx.behaviors.yyy] dans le controller. 
action_bar:
    config_btns:
        format: grouped #unique : un seul bouton, all : tts les boutons
        groups:
            waka.utils::lang.prod.produce: oc-icon-file-text-o
            waka.utils::lang.prod.send: oc-icon-external-link
            waka.utils::lang.prod.tools: oc-icon-wrench
        btns:

    partials: #Attention seul les variables modelId et modelClass (class du controller) sont disponible sans les partials.  
        test:
            url: $/waka/cloudis/controllers/montages/_test.htm



#     ##### SAUVEGARDE PURE ########

# modelClass: Waka\Cloudis\Models\Montage

# workflow: false 

# ###BREADCRUMP
# breadcrump:
#     inSettings: true 
#     indexUrl: waka/cloudis/montages
#     indexlabel: waka.cloudis::montage.title
#     title: waka.cloudis::montage.form_name

# ###TOOL_BAR
# tool_bar:
#     base:
#         create: 
#             show: true
#             permissions: [waka.cloudis.admin.super]
#             url: waka/cloudis/montages/create
#         reorder: 
#             show: false#  
#         delete: 
#             show: true
#             permissions: [waka.cloudis.admin.super]
#     config_btns:
#             format: all
#             btns:
# # #     config_lot:
#         format: all
#         btns: 
# # # # #     # partials: #Attention seul les variables modelId et modelClass (class du controller) sont disponible sans les partials.  
#     #     testbtns:
#     #         url: $/waka/cloudis/controllers/montages/_test_btns.htm

# ###ACTION_BAR Producteurs. Les behavior liée aux boutons doivent êtres instanciés implements = [waka.xxx.behaviors.yyy] dans le controller. 
# action_bar:
#     config_btns:
#         format: grouped #unique : un seul bouton, all : tts les boutons
#         groups:
#             waka.utils::lang.prod.produce: oc-icon-file-text-o
#             waka.utils::lang.prod.send: oc-icon-external-link
#             waka.utils::lang.prod.tools: oc-icon-wrench
#         btns:
# # # # # # # # # # 
#     # partials: #Attention seul les variables modelId et modelClass (class du controller) sont disponible sans les partials.  
#     #     name:
#     #         url: $/waka/cloudis/controllers/montages/_test_update.htm
